name: "driftctl-newlic-action"
author: "Maathor based on CloudSkiff"
description: "Run driftctl in your GitHub Actions workflow."

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  version:
    description: "The version of driftctl to install."
    required: false
    default: "latest"
  filter:
    description: "Is filter is required"
    required: false
    default: "false"
  tag_key:
    description: "Tag key to filter on"
    required: false
  tag_value:
    description: "Tag Value to filter on"
    required: false
  new_relic_licence_key:
    description: "New Relic licence KEY"
    required: true
  event_type_name:
    description: "New Relic CustomEvent Name"
    required: false
    default: "DriftDeployEvent"
  tfstate_s3_path:
    description: "s3 tfstate location"
    required: true
  aws_access_key_id:
    description: "aws access key id"
    required: true
  aws_secret_access_key:
    description: "aws secret access key"
    required: true
  aws_region:
    description: "aws region used"
    required: true
  env:
    description: "Staging"
    required: true
    default: "prod"
  github_repository:
    description: "{{ github.repository}}"
    required: true
  github_run_id:
    description: "{{ github.run_id }}"
    required: true
outputs:
  total_resources:
    description: "driftctl total resources output"
  total_changed:
    description: "driftctl total changed resources output"
  total_unmanaged:
    description: "driftctl total unmanaged resources output"
  total_managed:
    description: "driftctl total managed resources output"
  total_missing:
    description: "driftctl total missing resources output"
branding:
  icon: "activity"
  color: "blue"
